# fly.toml (VERSÃO FINAL PARA DEPLOY COM DOCKERFILE)

# Nome da sua aplicação no Fly.io
app = 'api-cnd' 

# Região principal onde as máquinas serão criadas
primary_region = 'gru'

# Define os comandos que cada processo irá executar.
# Estes comandos agora funcionarão pois o Dockerfile cria o ambiente .venv
[processes]
  app = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 api:app"
  worker = ".venv/bin/python worker.py"

# Define o disco persistente que será anexado às máquinas
[mounts]
  source = "data"
  destination = "/data"

# Define o serviço da API (web)
[[services]]
  processes = ["app"] # Diz que este serviço deve rodar o processo "app"
  protocol = "tcp"
  internal_port = 8080

  # Mapeia as portas da internet para a porta interna da aplicação
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Configuração da máquina virtual para a API
  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024

# Define o serviço do Worker (background)
[[services]]
  processes = ["worker"] # Diz que este serviço deve rodar o processo "worker"
  
  # Configuração da máquina virtual para o Worker
  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024