# fly.toml (VERSÃO FINAL E CORRETA)

app = 'api-cnd'
primary_region = 'gru'

[build]
  builder = "paketobuildpacks/builder:base"

# Define os comandos diretos e completos para cada processo
[processes]
  app = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 api:app"
  worker = ".venv/bin/python worker.py"

# Monta o disco persistente que será usado pelos serviços
[mounts]
  source = "data"
  destination = "/data"

# Define o serviço WEB, que vai rodar o processo 'app'
[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024

# Define o serviço WORKER, que vai rodar o processo 'worker'
[[services]]
  processes = ["worker"]
  
  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024