# fly.toml (VERSÃO FINAL COM ESTRUTURA MODERNA E CORRETA)

app = 'api-cnd' # Verifique se este é o nome do seu app
primary_region = 'gru'

# Define os comandos para cada processo
[processes]
  app = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app"
  worker = "python worker.py"

# Monta o disco persistente que será usado pelos serviços
[mounts]
  source = "data"
  destination = "/data"

# Define o serviço WEB, que vai rodar o processo 'app'
[[services]]
  processes = ["app"] # <-- Diz a este serviço para rodar o processo 'app'
  protocol = "tcp"
  internal_port = 8080

  # Mapeia as portas para a internet
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Configuração da máquina virtual para o serviço web
  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024

# Define o serviço WORKER, que vai rodar o processo 'worker'
[[services]]
  processes = ["worker"] # <-- Diz a este serviço para rodar o processo 'worker'
  
  # O worker não precisa de portas abertas para a internet

  # Configuração da máquina virtual para o worker
  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024