# fly.toml (VERSÃO FINAL E CORRETA)

app = 'api-cnd'
primary_region = 'gru'

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  app = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 api:app"
  worker = "python worker.py" # <-- Comando do worker corrigido para o padrão

[mounts]
  source = "data"
  destination = "/data"

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024

[[services]]
  processes = ["worker"]
  
  [services.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 1024