# render.yaml (VERSÃO FINAL E CORRETA DA ESTRUTURA)

# Declara os recursos que serão compartilhados primeiro
disks:
  - name: data            # Nome do nosso disco persistente
    sizeGB: 1           # Tamanho do disco (1GB está no plano gratuito)
    mountPath: /var/data  # Onde o disco será "montado"

services:
  # Serviço 1: A API Web, que usa o disco 'data'
  - type: web
    name: api-cnd-fiscal
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_PATH # Aponta para o banco de dados no disco
        value: /var/data/sistema_consultas2.db
    disk:
      name: data # Diz a este serviço para USAR o disco 'data'
      mountPath: /var/data # E onde montá-lo

  # Serviço 2: O Worker de Background, que usa o mesmo disco 'data'
  - type: worker
    name: api-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_PATH # Aponta para o mesmo banco de dados
        value: /var/data/sistema_consultas2.db
    disk:
      name: data # Diz a este serviço para USAR o mesmo disco 'data'
      mountPath: /var/data # E onde montá-lo